image: nixos/unstable

sources:
    - https://git.sr.ht/~tmayoff/opendds-nixpkgs#$GIT_REF
environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
tasks:
    - build: |
        cd opendds-nixpkgs
        nix build

